apiVersion: v1
kind: Service
metadata:
  name: reisdocumentmock
  labels:
    app: haal-centraal-reisdocument-bevragen-api
spec:
  selector:
    name: reisdocumentmock
  type: ClusterIP
  ports:
    - name: "5010"
      port: 5010
      targetPort: 5010
