apiVersion: v1
kind: Service
metadata:
  name: reisdocumentproxy
  labels:
    app: haal-centraal-reisdocument-bevragen-api
spec:
  selector:
    name: reisdocumentproxy
  type: LoadBalancer
  ports:
    - name: "5002"
      port: 5002
      targetPort: http
