/* 
 * Reisdocumenten
 *
 * API voor het ontsluiten van gegevens van reisdocumenten uit de GBA en RNI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReisdocumentenApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>ReisdocumentHal</returns>
        ReisdocumentHal ReisdocumentenReisdocumentnummer (string reisdocumentnummer);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>ApiResponse of ReisdocumentHal</returns>
        ApiResponse<ReisdocumentHal> ReisdocumentenReisdocumentnummerWithHttpInfo (string reisdocumentnummer);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReisdocumentenApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>Task of ReisdocumentHal</returns>
        System.Threading.Tasks.Task<ReisdocumentHal> ReisdocumentenReisdocumentnummerAsync (string reisdocumentnummer);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>Task of ApiResponse (ReisdocumentHal)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReisdocumentHal>> ReisdocumentenReisdocumentnummerAsyncWithHttpInfo (string reisdocumentnummer);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReisdocumentenApi : IReisdocumentenApiSync, IReisdocumentenApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ReisdocumentenApi : IReisdocumentenApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ReisdocumentenApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ReisdocumentenApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReisdocumentenApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ReisdocumentenApi(String basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReisdocumentenApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ReisdocumentenApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReisdocumentenApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ReisdocumentenApi(Org.OpenAPITools.Client.ISynchronousClient client,Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>ReisdocumentHal</returns>
        public ReisdocumentHal ReisdocumentenReisdocumentnummer (string reisdocumentnummer)
        {
             Org.OpenAPITools.Client.ApiResponse<ReisdocumentHal> localVarResponse = ReisdocumentenReisdocumentnummerWithHttpInfo(reisdocumentnummer);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>ApiResponse of ReisdocumentHal</returns>
        public Org.OpenAPITools.Client.ApiResponse< ReisdocumentHal > ReisdocumentenReisdocumentnummerWithHttpInfo (string reisdocumentnummer)
        {
            // verify the required parameter 'reisdocumentnummer' is set
            if (reisdocumentnummer == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'reisdocumentnummer' when calling ReisdocumentenApi->ReisdocumentenReisdocumentnummer");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/hal+json",
                "application/problem+json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("reisdocumentnummer", Org.OpenAPITools.Client.ClientUtils.ParameterToString(reisdocumentnummer)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get< ReisdocumentHal >("/reisdocumenten/{reisdocumentnummer}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReisdocumentenReisdocumentnummer", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>Task of ReisdocumentHal</returns>
        public async System.Threading.Tasks.Task<ReisdocumentHal> ReisdocumentenReisdocumentnummerAsync (string reisdocumentnummer)
        {
             Org.OpenAPITools.Client.ApiResponse<ReisdocumentHal> localVarResponse = await ReisdocumentenReisdocumentnummerAsyncWithHttpInfo(reisdocumentnummer);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>Task of ApiResponse (ReisdocumentHal)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<ReisdocumentHal>> ReisdocumentenReisdocumentnummerAsyncWithHttpInfo (string reisdocumentnummer)
        {
            // verify the required parameter 'reisdocumentnummer' is set
            if (reisdocumentnummer == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'reisdocumentnummer' when calling ReisdocumentenApi->ReisdocumentenReisdocumentnummer");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/hal+json",
                "application/problem+json"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            localVarRequestOptions.PathParameters.Add("reisdocumentnummer", Org.OpenAPITools.Client.ClientUtils.ParameterToString(reisdocumentnummer)); // path parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ReisdocumentHal>("/reisdocumenten/{reisdocumentnummer}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReisdocumentenReisdocumentnummer", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
