# coding: utf-8

"""
    Reisdocumenten

    API voor het ontsluiten van gegevens van reisdocumenten uit de GBA en RNI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class Reisdocument(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'aanduiding_inhouding_of_vermissing': 'AanduidingInhoudingVermissingReisdocumentEnum',
        'reisdocumentnummer': 'str',
        'autoriteit_afgifte': 'Waardetabel',
        'datum_einde_geldigheid': 'DatumOnvolledig',
        'datum_inhouding_of_vermissing': 'DatumOnvolledig',
        'datum_uitgifte': 'DatumOnvolledig',
        'soort_reisdocument': 'Waardetabel',
        'geheimhouding_persoonsgegevens': 'bool',
        'in_onderzoek': 'ReisdocumentInOnderzoek'
    }

    attribute_map = {
        'aanduiding_inhouding_of_vermissing': 'aanduidingInhoudingOfVermissing',
        'reisdocumentnummer': 'reisdocumentnummer',
        'autoriteit_afgifte': 'autoriteitAfgifte',
        'datum_einde_geldigheid': 'datumEindeGeldigheid',
        'datum_inhouding_of_vermissing': 'datumInhoudingOfVermissing',
        'datum_uitgifte': 'datumUitgifte',
        'soort_reisdocument': 'soortReisdocument',
        'geheimhouding_persoonsgegevens': 'geheimhoudingPersoonsgegevens',
        'in_onderzoek': 'inOnderzoek'
    }

    def __init__(self, aanduiding_inhouding_of_vermissing=None, reisdocumentnummer=None, autoriteit_afgifte=None, datum_einde_geldigheid=None, datum_inhouding_of_vermissing=None, datum_uitgifte=None, soort_reisdocument=None, geheimhouding_persoonsgegevens=None, in_onderzoek=None, local_vars_configuration=None):  # noqa: E501
        """Reisdocument - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._aanduiding_inhouding_of_vermissing = None
        self._reisdocumentnummer = None
        self._autoriteit_afgifte = None
        self._datum_einde_geldigheid = None
        self._datum_inhouding_of_vermissing = None
        self._datum_uitgifte = None
        self._soort_reisdocument = None
        self._geheimhouding_persoonsgegevens = None
        self._in_onderzoek = None
        self.discriminator = None

        if aanduiding_inhouding_of_vermissing is not None:
            self.aanduiding_inhouding_of_vermissing = aanduiding_inhouding_of_vermissing
        if reisdocumentnummer is not None:
            self.reisdocumentnummer = reisdocumentnummer
        if autoriteit_afgifte is not None:
            self.autoriteit_afgifte = autoriteit_afgifte
        if datum_einde_geldigheid is not None:
            self.datum_einde_geldigheid = datum_einde_geldigheid
        if datum_inhouding_of_vermissing is not None:
            self.datum_inhouding_of_vermissing = datum_inhouding_of_vermissing
        if datum_uitgifte is not None:
            self.datum_uitgifte = datum_uitgifte
        if soort_reisdocument is not None:
            self.soort_reisdocument = soort_reisdocument
        if geheimhouding_persoonsgegevens is not None:
            self.geheimhouding_persoonsgegevens = geheimhouding_persoonsgegevens
        if in_onderzoek is not None:
            self.in_onderzoek = in_onderzoek

    @property
    def aanduiding_inhouding_of_vermissing(self):
        """Gets the aanduiding_inhouding_of_vermissing of this Reisdocument.  # noqa: E501


        :return: The aanduiding_inhouding_of_vermissing of this Reisdocument.  # noqa: E501
        :rtype: AanduidingInhoudingVermissingReisdocumentEnum
        """
        return self._aanduiding_inhouding_of_vermissing

    @aanduiding_inhouding_of_vermissing.setter
    def aanduiding_inhouding_of_vermissing(self, aanduiding_inhouding_of_vermissing):
        """Sets the aanduiding_inhouding_of_vermissing of this Reisdocument.


        :param aanduiding_inhouding_of_vermissing: The aanduiding_inhouding_of_vermissing of this Reisdocument.  # noqa: E501
        :type: AanduidingInhoudingVermissingReisdocumentEnum
        """

        self._aanduiding_inhouding_of_vermissing = aanduiding_inhouding_of_vermissing

    @property
    def reisdocumentnummer(self):
        """Gets the reisdocumentnummer of this Reisdocument.  # noqa: E501

        Het nummer van het verstrekte Nederlandse reisdocument.  # noqa: E501

        :return: The reisdocumentnummer of this Reisdocument.  # noqa: E501
        :rtype: str
        """
        return self._reisdocumentnummer

    @reisdocumentnummer.setter
    def reisdocumentnummer(self, reisdocumentnummer):
        """Sets the reisdocumentnummer of this Reisdocument.

        Het nummer van het verstrekte Nederlandse reisdocument.  # noqa: E501

        :param reisdocumentnummer: The reisdocumentnummer of this Reisdocument.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                reisdocumentnummer is not None and len(reisdocumentnummer) > 9):
            raise ValueError("Invalid value for `reisdocumentnummer`, length must be less than or equal to `9`")  # noqa: E501

        self._reisdocumentnummer = reisdocumentnummer

    @property
    def autoriteit_afgifte(self):
        """Gets the autoriteit_afgifte of this Reisdocument.  # noqa: E501


        :return: The autoriteit_afgifte of this Reisdocument.  # noqa: E501
        :rtype: Waardetabel
        """
        return self._autoriteit_afgifte

    @autoriteit_afgifte.setter
    def autoriteit_afgifte(self, autoriteit_afgifte):
        """Sets the autoriteit_afgifte of this Reisdocument.


        :param autoriteit_afgifte: The autoriteit_afgifte of this Reisdocument.  # noqa: E501
        :type: Waardetabel
        """

        self._autoriteit_afgifte = autoriteit_afgifte

    @property
    def datum_einde_geldigheid(self):
        """Gets the datum_einde_geldigheid of this Reisdocument.  # noqa: E501


        :return: The datum_einde_geldigheid of this Reisdocument.  # noqa: E501
        :rtype: DatumOnvolledig
        """
        return self._datum_einde_geldigheid

    @datum_einde_geldigheid.setter
    def datum_einde_geldigheid(self, datum_einde_geldigheid):
        """Sets the datum_einde_geldigheid of this Reisdocument.


        :param datum_einde_geldigheid: The datum_einde_geldigheid of this Reisdocument.  # noqa: E501
        :type: DatumOnvolledig
        """

        self._datum_einde_geldigheid = datum_einde_geldigheid

    @property
    def datum_inhouding_of_vermissing(self):
        """Gets the datum_inhouding_of_vermissing of this Reisdocument.  # noqa: E501


        :return: The datum_inhouding_of_vermissing of this Reisdocument.  # noqa: E501
        :rtype: DatumOnvolledig
        """
        return self._datum_inhouding_of_vermissing

    @datum_inhouding_of_vermissing.setter
    def datum_inhouding_of_vermissing(self, datum_inhouding_of_vermissing):
        """Sets the datum_inhouding_of_vermissing of this Reisdocument.


        :param datum_inhouding_of_vermissing: The datum_inhouding_of_vermissing of this Reisdocument.  # noqa: E501
        :type: DatumOnvolledig
        """

        self._datum_inhouding_of_vermissing = datum_inhouding_of_vermissing

    @property
    def datum_uitgifte(self):
        """Gets the datum_uitgifte of this Reisdocument.  # noqa: E501


        :return: The datum_uitgifte of this Reisdocument.  # noqa: E501
        :rtype: DatumOnvolledig
        """
        return self._datum_uitgifte

    @datum_uitgifte.setter
    def datum_uitgifte(self, datum_uitgifte):
        """Sets the datum_uitgifte of this Reisdocument.


        :param datum_uitgifte: The datum_uitgifte of this Reisdocument.  # noqa: E501
        :type: DatumOnvolledig
        """

        self._datum_uitgifte = datum_uitgifte

    @property
    def soort_reisdocument(self):
        """Gets the soort_reisdocument of this Reisdocument.  # noqa: E501


        :return: The soort_reisdocument of this Reisdocument.  # noqa: E501
        :rtype: Waardetabel
        """
        return self._soort_reisdocument

    @soort_reisdocument.setter
    def soort_reisdocument(self, soort_reisdocument):
        """Sets the soort_reisdocument of this Reisdocument.


        :param soort_reisdocument: The soort_reisdocument of this Reisdocument.  # noqa: E501
        :type: Waardetabel
        """

        self._soort_reisdocument = soort_reisdocument

    @property
    def geheimhouding_persoonsgegevens(self):
        """Gets the geheimhouding_persoonsgegevens of this Reisdocument.  # noqa: E501

        Een aanduiding die aangeeft dat gegevens wel of niet verstrekt mogen worden. Indien true: op verzoek van deze persoon is het verstrekken van gegevens over deze persoon aan bepaalde derden niet toegestaan.  # noqa: E501

        :return: The geheimhouding_persoonsgegevens of this Reisdocument.  # noqa: E501
        :rtype: bool
        """
        return self._geheimhouding_persoonsgegevens

    @geheimhouding_persoonsgegevens.setter
    def geheimhouding_persoonsgegevens(self, geheimhouding_persoonsgegevens):
        """Sets the geheimhouding_persoonsgegevens of this Reisdocument.

        Een aanduiding die aangeeft dat gegevens wel of niet verstrekt mogen worden. Indien true: op verzoek van deze persoon is het verstrekken van gegevens over deze persoon aan bepaalde derden niet toegestaan.  # noqa: E501

        :param geheimhouding_persoonsgegevens: The geheimhouding_persoonsgegevens of this Reisdocument.  # noqa: E501
        :type: bool
        """

        self._geheimhouding_persoonsgegevens = geheimhouding_persoonsgegevens

    @property
    def in_onderzoek(self):
        """Gets the in_onderzoek of this Reisdocument.  # noqa: E501


        :return: The in_onderzoek of this Reisdocument.  # noqa: E501
        :rtype: ReisdocumentInOnderzoek
        """
        return self._in_onderzoek

    @in_onderzoek.setter
    def in_onderzoek(self, in_onderzoek):
        """Sets the in_onderzoek of this Reisdocument.


        :param in_onderzoek: The in_onderzoek of this Reisdocument.  # noqa: E501
        :type: ReisdocumentInOnderzoek
        """

        self._in_onderzoek = in_onderzoek

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Reisdocument):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Reisdocument):
            return True

        return self.to_dict() != other.to_dict()
