/*
 * Reisdocumenten
 * API voor het ontsluiten van gegevens van reisdocumenten uit de GBA en RNI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.DatumOnvolledig;

/**
 * Een groep van booleans om aan te geven welke gegevens van het reisdocument in onderzoek zijn. Als de hele categorie in onderzoek is worden alle rubrieken binnen die categorie op _true_ gezet. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/in_onderzoek.feature) .
 */
@ApiModel(description = "Een groep van booleans om aan te geven welke gegevens van het reisdocument in onderzoek zijn. Als de hele categorie in onderzoek is worden alle rubrieken binnen die categorie op _true_ gezet. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/in_onderzoek.feature) .")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-27T08:15:23.756Z[Etc/UTC]")
public class ReisdocumentInOnderzoek {
  public static final String SERIALIZED_NAME_AANDUIDING_INHOUDING_OF_VERMISSING = "aanduidingInhoudingOfVermissing";
  @SerializedName(SERIALIZED_NAME_AANDUIDING_INHOUDING_OF_VERMISSING)
  private Boolean aanduidingInhoudingOfVermissing;

  public static final String SERIALIZED_NAME_AUTORITEIT_AFGIFTE = "autoriteitAfgifte";
  @SerializedName(SERIALIZED_NAME_AUTORITEIT_AFGIFTE)
  private Boolean autoriteitAfgifte;

  public static final String SERIALIZED_NAME_DATUM_EINDE_GELDIGHEID = "datumEindeGeldigheid";
  @SerializedName(SERIALIZED_NAME_DATUM_EINDE_GELDIGHEID)
  private Boolean datumEindeGeldigheid;

  public static final String SERIALIZED_NAME_DATUM_INHOUDING_OF_VERMISSING = "datumInhoudingOfVermissing";
  @SerializedName(SERIALIZED_NAME_DATUM_INHOUDING_OF_VERMISSING)
  private Boolean datumInhoudingOfVermissing;

  public static final String SERIALIZED_NAME_DATUM_UITGIFTE = "datumUitgifte";
  @SerializedName(SERIALIZED_NAME_DATUM_UITGIFTE)
  private Boolean datumUitgifte;

  public static final String SERIALIZED_NAME_REISDOCUMENTNUMMER = "reisdocumentnummer";
  @SerializedName(SERIALIZED_NAME_REISDOCUMENTNUMMER)
  private Boolean reisdocumentnummer;

  public static final String SERIALIZED_NAME_SOORT_REISDOCUMENT = "soortReisdocument";
  @SerializedName(SERIALIZED_NAME_SOORT_REISDOCUMENT)
  private Boolean soortReisdocument;

  public static final String SERIALIZED_NAME_DATUM_INGANG_ONDERZOEK = "datumIngangOnderzoek";
  @SerializedName(SERIALIZED_NAME_DATUM_INGANG_ONDERZOEK)
  private DatumOnvolledig datumIngangOnderzoek;


  public ReisdocumentInOnderzoek aanduidingInhoudingOfVermissing(Boolean aanduidingInhoudingOfVermissing) {
    
    this.aanduidingInhoudingOfVermissing = aanduidingInhoudingOfVermissing;
    return this;
  }

   /**
   * Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
   * @return aanduidingInhoudingOfVermissing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.")

  public Boolean getAanduidingInhoudingOfVermissing() {
    return aanduidingInhoudingOfVermissing;
  }


  public void setAanduidingInhoudingOfVermissing(Boolean aanduidingInhoudingOfVermissing) {
    this.aanduidingInhoudingOfVermissing = aanduidingInhoudingOfVermissing;
  }


  public ReisdocumentInOnderzoek autoriteitAfgifte(Boolean autoriteitAfgifte) {
    
    this.autoriteitAfgifte = autoriteitAfgifte;
    return this;
  }

   /**
   * Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
   * @return autoriteitAfgifte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.")

  public Boolean getAutoriteitAfgifte() {
    return autoriteitAfgifte;
  }


  public void setAutoriteitAfgifte(Boolean autoriteitAfgifte) {
    this.autoriteitAfgifte = autoriteitAfgifte;
  }


  public ReisdocumentInOnderzoek datumEindeGeldigheid(Boolean datumEindeGeldigheid) {
    
    this.datumEindeGeldigheid = datumEindeGeldigheid;
    return this;
  }

   /**
   * Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
   * @return datumEindeGeldigheid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.")

  public Boolean getDatumEindeGeldigheid() {
    return datumEindeGeldigheid;
  }


  public void setDatumEindeGeldigheid(Boolean datumEindeGeldigheid) {
    this.datumEindeGeldigheid = datumEindeGeldigheid;
  }


  public ReisdocumentInOnderzoek datumInhoudingOfVermissing(Boolean datumInhoudingOfVermissing) {
    
    this.datumInhoudingOfVermissing = datumInhoudingOfVermissing;
    return this;
  }

   /**
   * Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
   * @return datumInhoudingOfVermissing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.")

  public Boolean getDatumInhoudingOfVermissing() {
    return datumInhoudingOfVermissing;
  }


  public void setDatumInhoudingOfVermissing(Boolean datumInhoudingOfVermissing) {
    this.datumInhoudingOfVermissing = datumInhoudingOfVermissing;
  }


  public ReisdocumentInOnderzoek datumUitgifte(Boolean datumUitgifte) {
    
    this.datumUitgifte = datumUitgifte;
    return this;
  }

   /**
   * Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
   * @return datumUitgifte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.")

  public Boolean getDatumUitgifte() {
    return datumUitgifte;
  }


  public void setDatumUitgifte(Boolean datumUitgifte) {
    this.datumUitgifte = datumUitgifte;
  }


  public ReisdocumentInOnderzoek reisdocumentnummer(Boolean reisdocumentnummer) {
    
    this.reisdocumentnummer = reisdocumentnummer;
    return this;
  }

   /**
   * Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
   * @return reisdocumentnummer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.")

  public Boolean getReisdocumentnummer() {
    return reisdocumentnummer;
  }


  public void setReisdocumentnummer(Boolean reisdocumentnummer) {
    this.reisdocumentnummer = reisdocumentnummer;
  }


  public ReisdocumentInOnderzoek soortReisdocument(Boolean soortReisdocument) {
    
    this.soortReisdocument = soortReisdocument;
    return this;
  }

   /**
   * Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
   * @return soortReisdocument
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.")

  public Boolean getSoortReisdocument() {
    return soortReisdocument;
  }


  public void setSoortReisdocument(Boolean soortReisdocument) {
    this.soortReisdocument = soortReisdocument;
  }


  public ReisdocumentInOnderzoek datumIngangOnderzoek(DatumOnvolledig datumIngangOnderzoek) {
    
    this.datumIngangOnderzoek = datumIngangOnderzoek;
    return this;
  }

   /**
   * Get datumIngangOnderzoek
   * @return datumIngangOnderzoek
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DatumOnvolledig getDatumIngangOnderzoek() {
    return datumIngangOnderzoek;
  }


  public void setDatumIngangOnderzoek(DatumOnvolledig datumIngangOnderzoek) {
    this.datumIngangOnderzoek = datumIngangOnderzoek;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReisdocumentInOnderzoek reisdocumentInOnderzoek = (ReisdocumentInOnderzoek) o;
    return Objects.equals(this.aanduidingInhoudingOfVermissing, reisdocumentInOnderzoek.aanduidingInhoudingOfVermissing) &&
        Objects.equals(this.autoriteitAfgifte, reisdocumentInOnderzoek.autoriteitAfgifte) &&
        Objects.equals(this.datumEindeGeldigheid, reisdocumentInOnderzoek.datumEindeGeldigheid) &&
        Objects.equals(this.datumInhoudingOfVermissing, reisdocumentInOnderzoek.datumInhoudingOfVermissing) &&
        Objects.equals(this.datumUitgifte, reisdocumentInOnderzoek.datumUitgifte) &&
        Objects.equals(this.reisdocumentnummer, reisdocumentInOnderzoek.reisdocumentnummer) &&
        Objects.equals(this.soortReisdocument, reisdocumentInOnderzoek.soortReisdocument) &&
        Objects.equals(this.datumIngangOnderzoek, reisdocumentInOnderzoek.datumIngangOnderzoek);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aanduidingInhoudingOfVermissing, autoriteitAfgifte, datumEindeGeldigheid, datumInhoudingOfVermissing, datumUitgifte, reisdocumentnummer, soortReisdocument, datumIngangOnderzoek);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReisdocumentInOnderzoek {\n");
    sb.append("    aanduidingInhoudingOfVermissing: ").append(toIndentedString(aanduidingInhoudingOfVermissing)).append("\n");
    sb.append("    autoriteitAfgifte: ").append(toIndentedString(autoriteitAfgifte)).append("\n");
    sb.append("    datumEindeGeldigheid: ").append(toIndentedString(datumEindeGeldigheid)).append("\n");
    sb.append("    datumInhoudingOfVermissing: ").append(toIndentedString(datumInhoudingOfVermissing)).append("\n");
    sb.append("    datumUitgifte: ").append(toIndentedString(datumUitgifte)).append("\n");
    sb.append("    reisdocumentnummer: ").append(toIndentedString(reisdocumentnummer)).append("\n");
    sb.append("    soortReisdocument: ").append(toIndentedString(soortReisdocument)).append("\n");
    sb.append("    datumIngangOnderzoek: ").append(toIndentedString(datumIngangOnderzoek)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

