/*
 * Reisdocumenten
 * API voor het ontsluiten van gegevens van reisdocumenten uit de GBA en RNI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.AanduidingInhoudingVermissingReisdocumentEnum;
import org.openapitools.client.model.DatumOnvolledig;
import org.openapitools.client.model.Reisdocument;
import org.openapitools.client.model.ReisdocumentHalAllOf;
import org.openapitools.client.model.ReisdocumentInOnderzoek;
import org.openapitools.client.model.ReisdocumentLinks;
import org.openapitools.client.model.Waardetabel;

/**
 * ReisdocumentHal
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-27T08:15:23.756Z[Etc/UTC]")
public class ReisdocumentHal {
  public static final String SERIALIZED_NAME_AANDUIDING_INHOUDING_OF_VERMISSING = "aanduidingInhoudingOfVermissing";
  @SerializedName(SERIALIZED_NAME_AANDUIDING_INHOUDING_OF_VERMISSING)
  private AanduidingInhoudingVermissingReisdocumentEnum aanduidingInhoudingOfVermissing;

  public static final String SERIALIZED_NAME_REISDOCUMENTNUMMER = "reisdocumentnummer";
  @SerializedName(SERIALIZED_NAME_REISDOCUMENTNUMMER)
  private String reisdocumentnummer;

  public static final String SERIALIZED_NAME_AUTORITEIT_AFGIFTE = "autoriteitAfgifte";
  @SerializedName(SERIALIZED_NAME_AUTORITEIT_AFGIFTE)
  private Waardetabel autoriteitAfgifte;

  public static final String SERIALIZED_NAME_DATUM_EINDE_GELDIGHEID = "datumEindeGeldigheid";
  @SerializedName(SERIALIZED_NAME_DATUM_EINDE_GELDIGHEID)
  private DatumOnvolledig datumEindeGeldigheid;

  public static final String SERIALIZED_NAME_DATUM_INHOUDING_OF_VERMISSING = "datumInhoudingOfVermissing";
  @SerializedName(SERIALIZED_NAME_DATUM_INHOUDING_OF_VERMISSING)
  private DatumOnvolledig datumInhoudingOfVermissing;

  public static final String SERIALIZED_NAME_DATUM_UITGIFTE = "datumUitgifte";
  @SerializedName(SERIALIZED_NAME_DATUM_UITGIFTE)
  private DatumOnvolledig datumUitgifte;

  public static final String SERIALIZED_NAME_SOORT_REISDOCUMENT = "soortReisdocument";
  @SerializedName(SERIALIZED_NAME_SOORT_REISDOCUMENT)
  private Waardetabel soortReisdocument;

  public static final String SERIALIZED_NAME_GEHEIMHOUDING_PERSOONSGEGEVENS = "geheimhoudingPersoonsgegevens";
  @SerializedName(SERIALIZED_NAME_GEHEIMHOUDING_PERSOONSGEGEVENS)
  private Boolean geheimhoudingPersoonsgegevens;

  public static final String SERIALIZED_NAME_IN_ONDERZOEK = "inOnderzoek";
  @SerializedName(SERIALIZED_NAME_IN_ONDERZOEK)
  private ReisdocumentInOnderzoek inOnderzoek;

  public static final String SERIALIZED_NAME_LINKS = "_links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  private ReisdocumentLinks links;


  public ReisdocumentHal aanduidingInhoudingOfVermissing(AanduidingInhoudingVermissingReisdocumentEnum aanduidingInhoudingOfVermissing) {
    
    this.aanduidingInhoudingOfVermissing = aanduidingInhoudingOfVermissing;
    return this;
  }

   /**
   * Get aanduidingInhoudingOfVermissing
   * @return aanduidingInhoudingOfVermissing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AanduidingInhoudingVermissingReisdocumentEnum getAanduidingInhoudingOfVermissing() {
    return aanduidingInhoudingOfVermissing;
  }


  public void setAanduidingInhoudingOfVermissing(AanduidingInhoudingVermissingReisdocumentEnum aanduidingInhoudingOfVermissing) {
    this.aanduidingInhoudingOfVermissing = aanduidingInhoudingOfVermissing;
  }


  public ReisdocumentHal reisdocumentnummer(String reisdocumentnummer) {
    
    this.reisdocumentnummer = reisdocumentnummer;
    return this;
  }

   /**
   * Het nummer van het verstrekte Nederlandse reisdocument.
   * @return reisdocumentnummer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "546376728", value = "Het nummer van het verstrekte Nederlandse reisdocument.")

  public String getReisdocumentnummer() {
    return reisdocumentnummer;
  }


  public void setReisdocumentnummer(String reisdocumentnummer) {
    this.reisdocumentnummer = reisdocumentnummer;
  }


  public ReisdocumentHal autoriteitAfgifte(Waardetabel autoriteitAfgifte) {
    
    this.autoriteitAfgifte = autoriteitAfgifte;
    return this;
  }

   /**
   * Get autoriteitAfgifte
   * @return autoriteitAfgifte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Waardetabel getAutoriteitAfgifte() {
    return autoriteitAfgifte;
  }


  public void setAutoriteitAfgifte(Waardetabel autoriteitAfgifte) {
    this.autoriteitAfgifte = autoriteitAfgifte;
  }


  public ReisdocumentHal datumEindeGeldigheid(DatumOnvolledig datumEindeGeldigheid) {
    
    this.datumEindeGeldigheid = datumEindeGeldigheid;
    return this;
  }

   /**
   * Get datumEindeGeldigheid
   * @return datumEindeGeldigheid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DatumOnvolledig getDatumEindeGeldigheid() {
    return datumEindeGeldigheid;
  }


  public void setDatumEindeGeldigheid(DatumOnvolledig datumEindeGeldigheid) {
    this.datumEindeGeldigheid = datumEindeGeldigheid;
  }


  public ReisdocumentHal datumInhoudingOfVermissing(DatumOnvolledig datumInhoudingOfVermissing) {
    
    this.datumInhoudingOfVermissing = datumInhoudingOfVermissing;
    return this;
  }

   /**
   * Get datumInhoudingOfVermissing
   * @return datumInhoudingOfVermissing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DatumOnvolledig getDatumInhoudingOfVermissing() {
    return datumInhoudingOfVermissing;
  }


  public void setDatumInhoudingOfVermissing(DatumOnvolledig datumInhoudingOfVermissing) {
    this.datumInhoudingOfVermissing = datumInhoudingOfVermissing;
  }


  public ReisdocumentHal datumUitgifte(DatumOnvolledig datumUitgifte) {
    
    this.datumUitgifte = datumUitgifte;
    return this;
  }

   /**
   * Get datumUitgifte
   * @return datumUitgifte
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DatumOnvolledig getDatumUitgifte() {
    return datumUitgifte;
  }


  public void setDatumUitgifte(DatumOnvolledig datumUitgifte) {
    this.datumUitgifte = datumUitgifte;
  }


  public ReisdocumentHal soortReisdocument(Waardetabel soortReisdocument) {
    
    this.soortReisdocument = soortReisdocument;
    return this;
  }

   /**
   * Get soortReisdocument
   * @return soortReisdocument
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Waardetabel getSoortReisdocument() {
    return soortReisdocument;
  }


  public void setSoortReisdocument(Waardetabel soortReisdocument) {
    this.soortReisdocument = soortReisdocument;
  }


  public ReisdocumentHal geheimhoudingPersoonsgegevens(Boolean geheimhoudingPersoonsgegevens) {
    
    this.geheimhoudingPersoonsgegevens = geheimhoudingPersoonsgegevens;
    return this;
  }

   /**
   * Een aanduiding die aangeeft dat gegevens wel of niet verstrekt mogen worden. Indien true: op verzoek van deze persoon is het verstrekken van gegevens over deze persoon aan bepaalde derden niet toegestaan.
   * @return geheimhoudingPersoonsgegevens
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Een aanduiding die aangeeft dat gegevens wel of niet verstrekt mogen worden. Indien true: op verzoek van deze persoon is het verstrekken van gegevens over deze persoon aan bepaalde derden niet toegestaan.")

  public Boolean getGeheimhoudingPersoonsgegevens() {
    return geheimhoudingPersoonsgegevens;
  }


  public void setGeheimhoudingPersoonsgegevens(Boolean geheimhoudingPersoonsgegevens) {
    this.geheimhoudingPersoonsgegevens = geheimhoudingPersoonsgegevens;
  }


  public ReisdocumentHal inOnderzoek(ReisdocumentInOnderzoek inOnderzoek) {
    
    this.inOnderzoek = inOnderzoek;
    return this;
  }

   /**
   * Get inOnderzoek
   * @return inOnderzoek
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ReisdocumentInOnderzoek getInOnderzoek() {
    return inOnderzoek;
  }


  public void setInOnderzoek(ReisdocumentInOnderzoek inOnderzoek) {
    this.inOnderzoek = inOnderzoek;
  }


  public ReisdocumentHal links(ReisdocumentLinks links) {
    
    this.links = links;
    return this;
  }

   /**
   * Get links
   * @return links
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ReisdocumentLinks getLinks() {
    return links;
  }


  public void setLinks(ReisdocumentLinks links) {
    this.links = links;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReisdocumentHal reisdocumentHal = (ReisdocumentHal) o;
    return Objects.equals(this.aanduidingInhoudingOfVermissing, reisdocumentHal.aanduidingInhoudingOfVermissing) &&
        Objects.equals(this.reisdocumentnummer, reisdocumentHal.reisdocumentnummer) &&
        Objects.equals(this.autoriteitAfgifte, reisdocumentHal.autoriteitAfgifte) &&
        Objects.equals(this.datumEindeGeldigheid, reisdocumentHal.datumEindeGeldigheid) &&
        Objects.equals(this.datumInhoudingOfVermissing, reisdocumentHal.datumInhoudingOfVermissing) &&
        Objects.equals(this.datumUitgifte, reisdocumentHal.datumUitgifte) &&
        Objects.equals(this.soortReisdocument, reisdocumentHal.soortReisdocument) &&
        Objects.equals(this.geheimhoudingPersoonsgegevens, reisdocumentHal.geheimhoudingPersoonsgegevens) &&
        Objects.equals(this.inOnderzoek, reisdocumentHal.inOnderzoek) &&
        Objects.equals(this.links, reisdocumentHal.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aanduidingInhoudingOfVermissing, reisdocumentnummer, autoriteitAfgifte, datumEindeGeldigheid, datumInhoudingOfVermissing, datumUitgifte, soortReisdocument, geheimhoudingPersoonsgegevens, inOnderzoek, links);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReisdocumentHal {\n");
    sb.append("    aanduidingInhoudingOfVermissing: ").append(toIndentedString(aanduidingInhoudingOfVermissing)).append("\n");
    sb.append("    reisdocumentnummer: ").append(toIndentedString(reisdocumentnummer)).append("\n");
    sb.append("    autoriteitAfgifte: ").append(toIndentedString(autoriteitAfgifte)).append("\n");
    sb.append("    datumEindeGeldigheid: ").append(toIndentedString(datumEindeGeldigheid)).append("\n");
    sb.append("    datumInhoudingOfVermissing: ").append(toIndentedString(datumInhoudingOfVermissing)).append("\n");
    sb.append("    datumUitgifte: ").append(toIndentedString(datumUitgifte)).append("\n");
    sb.append("    soortReisdocument: ").append(toIndentedString(soortReisdocument)).append("\n");
    sb.append("    geheimhoudingPersoonsgegevens: ").append(toIndentedString(geheimhoudingPersoonsgegevens)).append("\n");
    sb.append("    inOnderzoek: ").append(toIndentedString(inOnderzoek)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

