version: '3.7'

services:
  postgres:
    container_name: db
    image: db-ci
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    networks:
      - reisdocumenten-api-network

networks:
  reisdocumenten-api-network:
   name: reisdocumenten-api-network
