version: '3.4'

services:
  reisdocumentproxy:
    container_name: reisdocumentproxy
    image: ghcr.io/brp-api/haal-centraal-reisdocument-bevragen-proxy:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5000
      - Ecs__Path=/var/log/reisdocumenten-proxy.json
      # - Ecs__FileSizeLimitBytes=10240
      - Ecs__RetainedFileCountLimit=5
      - Routes__0__DownstreamScheme=http
      - Routes__0__DownstreamHostAndPorts__0__Host=haalcentraal_reisdocumenten_api
      - Routes__0__DownstreamHostAndPorts__0__Port=80
    ports:
      - "5002:5000"
    volumes:
      - ../test-data/logs:/var/log
    networks:
      - reisdocumenten-api-network

networks:
  reisdocumenten-api-network:
    name: reisdocumenten-api-network
