version: '3.7'

services:
  haalcentraal_reisdocumenten_api:
    container_name: haalcentraal_reisdocumenten_api
    image: haalcentraal.azurecr.io/gba-reisdocumenten-api:2.0.2
    networks:
      - reisdocumenten-api-network
    environment:
      - Database__ConnectionString=Host=postgres;port=5432;Username=root;Password=root;Database=rvig_haalcentraal_testdata
      - HaalcentraalApi__MaxSearchResults=10
      - ASPNETCORE_URLS=http://+;
      - AuthenticationTypes=Basic
      # - AuthenticationTypes=jwtbearer
      - Serilog__LogLevel__Default=Information
    ports:
      - "8001:80"

networks:
  reisdocumenten-api-network:
   name: reisdocumenten-api-network
