version: '3.4'

services:
  reisdocumentproxy-2:
    container_name: reisdocumentproxy-2
    image: ghcr.io/brp-api/haal-centraal-reisdocument-bevragen-proxy:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5000
      - Routes__0__DownstreamScheme=http
      - Routes__0__DownstreamHostAndPorts__0__Host=reisdocumentproxy
      - Routes__0__DownstreamHostAndPorts__0__Port=5000
    ports:
      - "5003:5000"
    networks:
      - reisdocumenten-api-network

networks:
  reisdocumenten-api-network:
    name: reisdocumenten-api-network
