version: '3.7'

services:
  haalcentraal_reisdocumenten_api:
    container_name: haalcentraal_reisdocumenten_api
    image: haalcentraal.azurecr.io/gba-reisdocumenten-api:2.0.10-2024052101
    environment:
      - Database__Host=postgres
      - Database__Username=root
      - Database__Password=root
      - Database__Database=rvig_haalcentraal_testdata
      - HaalcentraalApi__MaxSearchResults=10
      - ASPNETCORE_URLS=http://+;
      - Serilog__LogLevel__Default=Information
      - ProtocolleringAuthorization__UseAuthorizationChecks=false
      - ProtocolleringAuthorization__UseProtocollering=false
      - Ecs__Path=/var/log/brp-api.json
      - Ecs__FileSizeLimitBytes=10240
      - Ecs__RetainedFileCountLimit=5
    ports:
      - "8001:80"
    volumes:
      - ../test-data/logs:/var/log
    networks:
      - reisdocumenten-api-network

networks:
  reisdocumenten-api-network:
   name: reisdocumenten-api-network
