/* 
 * Reisdocumenten
 *
 * API voor het ontsluiten van gegevens van reisdocumenten uit de GBA en RNI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Een groep van booleans om aan te geven welke gegevens van het reisdocument in onderzoek zijn. Als de hele categorie in onderzoek is worden alle rubrieken binnen die categorie op _true_ gezet. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/in_onderzoek.feature) .
    /// </summary>
    [DataContract]
    public partial class ReisdocumentInOnderzoek :  IEquatable<ReisdocumentInOnderzoek>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReisdocumentInOnderzoek" /> class.
        /// </summary>
        /// <param name="aanduidingInhoudingOfVermissing">Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is..</param>
        /// <param name="autoriteitAfgifte">Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is..</param>
        /// <param name="datumEindeGeldigheid">Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is..</param>
        /// <param name="datumInhoudingOfVermissing">Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is..</param>
        /// <param name="datumUitgifte">Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is..</param>
        /// <param name="reisdocumentnummer">Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is..</param>
        /// <param name="soortReisdocument">Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is..</param>
        /// <param name="datumIngangOnderzoek">datumIngangOnderzoek.</param>
        public ReisdocumentInOnderzoek(bool aanduidingInhoudingOfVermissing = default(bool), bool autoriteitAfgifte = default(bool), bool datumEindeGeldigheid = default(bool), bool datumInhoudingOfVermissing = default(bool), bool datumUitgifte = default(bool), bool reisdocumentnummer = default(bool), bool soortReisdocument = default(bool), DatumOnvolledig datumIngangOnderzoek = default(DatumOnvolledig))
        {
            this.AanduidingInhoudingOfVermissing = aanduidingInhoudingOfVermissing;
            this.AutoriteitAfgifte = autoriteitAfgifte;
            this.DatumEindeGeldigheid = datumEindeGeldigheid;
            this.DatumInhoudingOfVermissing = datumInhoudingOfVermissing;
            this.DatumUitgifte = datumUitgifte;
            this.Reisdocumentnummer = reisdocumentnummer;
            this.SoortReisdocument = soortReisdocument;
            this.DatumIngangOnderzoek = datumIngangOnderzoek;
        }
        
        /// <summary>
        /// Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
        /// </summary>
        /// <value>Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.</value>
        [DataMember(Name="aanduidingInhoudingOfVermissing", EmitDefaultValue=false)]
        public bool AanduidingInhoudingOfVermissing { get; set; }

        /// <summary>
        /// Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
        /// </summary>
        /// <value>Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.</value>
        [DataMember(Name="autoriteitAfgifte", EmitDefaultValue=false)]
        public bool AutoriteitAfgifte { get; set; }

        /// <summary>
        /// Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
        /// </summary>
        /// <value>Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.</value>
        [DataMember(Name="datumEindeGeldigheid", EmitDefaultValue=false)]
        public bool DatumEindeGeldigheid { get; set; }

        /// <summary>
        /// Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
        /// </summary>
        /// <value>Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.</value>
        [DataMember(Name="datumInhoudingOfVermissing", EmitDefaultValue=false)]
        public bool DatumInhoudingOfVermissing { get; set; }

        /// <summary>
        /// Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
        /// </summary>
        /// <value>Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.</value>
        [DataMember(Name="datumUitgifte", EmitDefaultValue=false)]
        public bool DatumUitgifte { get; set; }

        /// <summary>
        /// Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
        /// </summary>
        /// <value>Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.</value>
        [DataMember(Name="reisdocumentnummer", EmitDefaultValue=false)]
        public bool Reisdocumentnummer { get; set; }

        /// <summary>
        /// Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.
        /// </summary>
        /// <value>Indicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is.</value>
        [DataMember(Name="soortReisdocument", EmitDefaultValue=false)]
        public bool SoortReisdocument { get; set; }

        /// <summary>
        /// Gets or Sets DatumIngangOnderzoek
        /// </summary>
        [DataMember(Name="datumIngangOnderzoek", EmitDefaultValue=false)]
        public DatumOnvolledig DatumIngangOnderzoek { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReisdocumentInOnderzoek {\n");
            sb.Append("  AanduidingInhoudingOfVermissing: ").Append(AanduidingInhoudingOfVermissing).Append("\n");
            sb.Append("  AutoriteitAfgifte: ").Append(AutoriteitAfgifte).Append("\n");
            sb.Append("  DatumEindeGeldigheid: ").Append(DatumEindeGeldigheid).Append("\n");
            sb.Append("  DatumInhoudingOfVermissing: ").Append(DatumInhoudingOfVermissing).Append("\n");
            sb.Append("  DatumUitgifte: ").Append(DatumUitgifte).Append("\n");
            sb.Append("  Reisdocumentnummer: ").Append(Reisdocumentnummer).Append("\n");
            sb.Append("  SoortReisdocument: ").Append(SoortReisdocument).Append("\n");
            sb.Append("  DatumIngangOnderzoek: ").Append(DatumIngangOnderzoek).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReisdocumentInOnderzoek);
        }

        /// <summary>
        /// Returns true if ReisdocumentInOnderzoek instances are equal
        /// </summary>
        /// <param name="input">Instance of ReisdocumentInOnderzoek to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReisdocumentInOnderzoek input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AanduidingInhoudingOfVermissing == input.AanduidingInhoudingOfVermissing ||
                    (this.AanduidingInhoudingOfVermissing != null &&
                    this.AanduidingInhoudingOfVermissing.Equals(input.AanduidingInhoudingOfVermissing))
                ) && 
                (
                    this.AutoriteitAfgifte == input.AutoriteitAfgifte ||
                    (this.AutoriteitAfgifte != null &&
                    this.AutoriteitAfgifte.Equals(input.AutoriteitAfgifte))
                ) && 
                (
                    this.DatumEindeGeldigheid == input.DatumEindeGeldigheid ||
                    (this.DatumEindeGeldigheid != null &&
                    this.DatumEindeGeldigheid.Equals(input.DatumEindeGeldigheid))
                ) && 
                (
                    this.DatumInhoudingOfVermissing == input.DatumInhoudingOfVermissing ||
                    (this.DatumInhoudingOfVermissing != null &&
                    this.DatumInhoudingOfVermissing.Equals(input.DatumInhoudingOfVermissing))
                ) && 
                (
                    this.DatumUitgifte == input.DatumUitgifte ||
                    (this.DatumUitgifte != null &&
                    this.DatumUitgifte.Equals(input.DatumUitgifte))
                ) && 
                (
                    this.Reisdocumentnummer == input.Reisdocumentnummer ||
                    (this.Reisdocumentnummer != null &&
                    this.Reisdocumentnummer.Equals(input.Reisdocumentnummer))
                ) && 
                (
                    this.SoortReisdocument == input.SoortReisdocument ||
                    (this.SoortReisdocument != null &&
                    this.SoortReisdocument.Equals(input.SoortReisdocument))
                ) && 
                (
                    this.DatumIngangOnderzoek == input.DatumIngangOnderzoek ||
                    (this.DatumIngangOnderzoek != null &&
                    this.DatumIngangOnderzoek.Equals(input.DatumIngangOnderzoek))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AanduidingInhoudingOfVermissing != null)
                    hashCode = hashCode * 59 + this.AanduidingInhoudingOfVermissing.GetHashCode();
                if (this.AutoriteitAfgifte != null)
                    hashCode = hashCode * 59 + this.AutoriteitAfgifte.GetHashCode();
                if (this.DatumEindeGeldigheid != null)
                    hashCode = hashCode * 59 + this.DatumEindeGeldigheid.GetHashCode();
                if (this.DatumInhoudingOfVermissing != null)
                    hashCode = hashCode * 59 + this.DatumInhoudingOfVermissing.GetHashCode();
                if (this.DatumUitgifte != null)
                    hashCode = hashCode * 59 + this.DatumUitgifte.GetHashCode();
                if (this.Reisdocumentnummer != null)
                    hashCode = hashCode * 59 + this.Reisdocumentnummer.GetHashCode();
                if (this.SoortReisdocument != null)
                    hashCode = hashCode * 59 + this.SoortReisdocument.GetHashCode();
                if (this.DatumIngangOnderzoek != null)
                    hashCode = hashCode * 59 + this.DatumIngangOnderzoek.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
