openapi: 3.0.3
info:
  title: Filter definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Field:
      description: |
        Het pad naar een gewenst veld in punt-gescheiden formaat. Bijvoorbeeld "burgerservicenummer", "geboorte.datum", "partners.naam.voornamen".
      type: string
      pattern: ^[a-zA-Z0-9\._]{1,200}$
