openapi: 3.0.0
servers:
  - description: |
                  APILAB testserver
    url: https://www.haalcentraal.nl/haalcentraal/api/brp
info:
  title: Reisdocumenten
  description: |
                API voor het ontsluiten van gegevens van reisdocumenten uit de GBA en RNI.
  version: "0.0.1 (develop)"
  contact:
    url: https://github.com/VNG-Realisatie/Haal-Centraal-Reisdocumenten-bevragen
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
tags:
  - name: Reisdocumenten
paths:
  /reisdocumenten/{reisdocumentnummer}:
    get:
      operationId: GetReisdocument
      summary: Raadpleeg een reisdocument
      description: |
                    Raadpleeg een Reisdocument.
                    Gebruik de fields parameter als je alleen specifieke velden in het antwoord wil zien, [zie functionele specificaties fields-parameter](https://github.com/VNG-Realisatie/Haal-Centraal-Reisdocumenten-bevragen/blob/v1.0.0/features/fields_extensie.feature).

      parameters:
        - in: path
          name: reisdocumentnummer
          required: true
          schema:
            type: string
            maxLength: 9
        - $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/parameters/fields"
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/headers/warning"
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/ReisdocumentHal'
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/403"
        '404':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/404"
        '406':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/406"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/responses/default"
      tags:
      - Reisdocumenten
components:
  schemas:
    Reisdocument:
      type: "object"
      description: |
                    Een document dat vereist is voor reizen naar het buitenland
                    * **datumEindeGeldigheid** : De datum waarop een Nederlands reisdocument, dat aan de ingeschrevene is verstrekt of waarin de ingeschrevene is bijgeschreven, zijn geldigheid verliest.
                    * **datumInhoudingOfVermissing**: De datum waarop een Nederlands reisdocument is vermist, ingehouden, ingeleverd, dan wel van rechtswege is vervallen.
                    * **datumUitgifte** : De datum waarop het Nederlands reisdocument is uitgegeven of de datum van bijschrijving van de ingeschrevene in een Nederlands reisdocument.
                    * **autoriteitAfgifte** : Tabel Autoriteit van afgifte Nederlands reisdocument, die aangeeft welke autoriteit het Nederlands reisdocument heeft verstrekt of de bijschrijving heeft verricht.
                    * **aanduidingInhoudingOfVermissing** : Een aanduiding dat een Nederlands reisdocument is vermist, ingehouden, ingeleverd, dan wel van rechtswege is vervallen.
                    * **soortReisdocument** : Tabel Nederlands reisdocument, die aangeeft welk Nederlandse reisdocument is verstrekt of in welk reisdocument de ingeschrevene is bijgeschreven.
      properties:
        aanduidingInhoudingOfVermissing:
          $ref: "#/components/schemas/AanduidingInhoudingVermissingReisdocumentEnum"
        reisdocumentnummer:
          type: "string"
          title: "Reisdocumentnummer"
          description: |
                        Het nummer van het verstrekte Nederlandse reisdocument.
          maxLength: 9
          example: "546376728"
        autoriteitAfgifte:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel"
        datumEindeGeldigheid:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/DatumOnvolledig"
        datumInhoudingOfVermissing:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/DatumOnvolledig"
        datumUitgifte:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/DatumOnvolledig"
        soortReisdocument:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/Waardetabel"
        geheimhoudingPersoonsgegevens:
          type: "boolean"
          title: "Indicatie geheim"
          description: |
                        Een aanduiding die aangeeft dat gegevens wel of niet verstrektmogen worden. Indien true: op verzoek van deze persoon is het verstrekken van gegevens over deze persoon aan bepaalde derden niet toegestaan.
        inOnderzoek:
          $ref: "#/components/schemas/ReisdocumentInOnderzoek"
    ReisdocumentHal:
      allOf:
        - $ref: '#/components/schemas/Reisdocument'
        - properties:
            _links:
              $ref: "#/components/schemas/ReisdocumentLinks"
    ReisdocumentLinks:
      type: "object"
      properties:
        self:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/HalLink"
        ingeschrevenPersoon:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/HalLink"
    AanduidingInhoudingVermissingReisdocumentEnum:
      type: "string"
      description: |
                    De mogelijke waarden van de aanduiding van inhouding of vermissing van een Nederlands reisdocument. Zie logisch ontwerp BRP bij de stamtabellen:
                    * `ingehouden_of_ingeleverd` - I
                    * `vermist` - V
                    * `rechtswege` - R
                    * `niet_in_bezit_van` - N"
      enum:
      - "ingehouden_of_ingeleverd"
      - "vermist"
      - "rechtswege"
      - "niet_in_bezit_van"
    ReisdocumentInOnderzoek:
      type: "object"
      description:  |
                      Geeft aan welke gegevens over de naam in onderzoek zijn. Zie de [functionele specificaties](https://github.com/VNG-Realisatie/Haal-Centraal-Reisdocumenten-bevragen/blob/v1.0.0/features/in_onderzoek.feature)
      properties:
        aanduidingInhoudingOfVermissing:
          type: "boolean"
        autoriteitAfgifte:
          type: "boolean"
        datumEindeGeldigheid:
          type: "boolean"
        datumInhoudingOfVermissing:
          type: "boolean"
        datumUitgifte:
          type: "boolean"
        reisdocumentnummer:
          type: "boolean"
        soortReisdocument:
          type: "boolean"
        datumIngangOnderzoek:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.2.0/api-specificatie/common.yaml#/components/schemas/DatumOnvolledig"
