openapi: 3.0.3
info:
  title: Persoon definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Burgerservicenummer:
      type: string
      pattern: ^[0-9]{9}$
      example: "555555021"
    GbaGeheimhoudingPersoonsgegevens:
      type: integer
    GeheimhoudingPersoonsgegevens:
      description: |
        Gegevens mogen niet worden verstrekt aan derden / maatschappelijke instellingen.
      type: boolean
    GemeenteVanInschrijving:
      description: |
        Een code die aangeeft in welke gemeente de persoon woont, of de laatste gemeente waar de persoon heeft gewoond, of de gemeente waar de persoon voor het eerst is ingeschreven.
      type: string
      pattern: ^[0-9]{4}$
      example: "0518"
