openapi: 3.0.3
info:
  title: Reisdocument definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Reisdocumentnummer:
      type: string
      pattern: ^[a-zA-Z0-9]{9}$
    Burgerservicenummer:
      type: string
      pattern: ^[0-9]{9}$
      example: "555555021"
    AanduidingInhoudingOfVermissing:
      type: string
      pattern: ^(I|R|V|\.)$
    SoortReisdocument:
      type: string
      description: |
            Een code voor het soort reisdocument. Wordt gevuld met een code die voorkomen in de tabel 'Nederlands_Reisdocument' uit de Haal-Centraal-BRP-tabellen-bevragen API.
      pattern: ^[A-Z]{2}$
    OpschortingBijhouding:
      type: object
      properties:
        reden:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
    OmschrijvingVerdrag:
      type: string
      description: |
        Omschrijving van het verdrag op basis waarvan een zusterorganisatie in het buitenland de gegevens bij de RNI-deelnemer heeft aangeleverd.
      pattern: ^[a-zA-Z0-9À-ž \.\-\']{1,50}$
    OmschrijvingVerificatie:
      type: string
      description: |
        Omschrijving van de verificatie van de rni-gegevens
      pattern: ^[a-zA-Z0-9À-ž \.\-\']{1,50}$
    GbaVerificatie:
      type: object
      properties:
        datum:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        omschrijving:
          $ref: '#/components/schemas/OmschrijvingVerificatie'
    Verificatie:
      type: object
      properties:
        datum:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
        omschrijving:
          $ref: '#/components/schemas/OmschrijvingVerificatie'
    RniDeelnemer:
      type: object
      properties:
        deelnemer:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        omschrijvingVerdrag:
          $ref: '#/components/schemas/OmschrijvingVerdrag'
    Reisdocument:
      type: object
      description: |
                    Een document dat nodig is voor reizen naar het buitenland.

                    indicatieGeldig geeft aan of het reisdocument op dit moment nog geldig en in het bezit van de persoon is. Wordt gevuld op basis van de waarden die voorkomen in de tabel 'Geldig_Reisdocument' uit de Haal-Centraal-BRP-tabellen-bevragen API.
      properties:
        reisdocumentnummer:
          $ref: '#/components/schemas/Reisdocumentnummer' 
        indicatieGeldig:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
        verificatie:
          $ref: '#/components/schemas/Verificatie'
        rni:
          $ref: '#/components/schemas/RniDeelnemer'
    ReisdocumentUitgebreid:
      allOf:
        - $ref: '#/components/schemas/Reisdocument'
        - type: object
          description: |
                        Een document dat nodig is voor reizen naar het buitenland.

                        - indicatieGeldig geeft aan of het reisdocument op dit moment nog geldig en in het bezit van de persoon is. Wordt gevuld op basis van de waarden die voorkomen in de tabel 'Geldig_Reisdocument' uit de Haal-Centraal-BRP-tabellen-bevragen API.
                        - soortReisdocument wordt gevuld op basis van de waarden die voorkomen in de tabel 'Nederlands_Reisdocument' uit de Haal-Centraal-BRP-tabellen-bevragen API.
          properties:
            soortReisdocument:
              $ref: 'common.yaml#/components/schemas/Waardetabel'
            datumEindeGeldigheid:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    GbaReisdocument:
      type: object
      description: |
          Gegevens van een reisdocument die nodig zijn om te bepalen of het reisdocument nog geldig en in het bezit van de houder is, plus de identificatie van de houder.
      properties:
        reisdocumentnummer:
          $ref: '#/components/schemas/Reisdocumentnummer'
        soortReisdocument:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        datumEindeGeldigheid:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        datumInhoudingOfVermissing:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        aanduidingInhoudingOfVermissing:
          $ref: '#/components/schemas/AanduidingInhoudingOfVermissing'
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
        opschortingBijhouding:
          $ref: '#/components/schemas/OpschortingBijhouding'
        verificatie:
          $ref: '#/components/schemas/GbaVerificatie'
        rni:
          $ref: '#/components/schemas/RniDeelnemer'
    ReisdocumentenQuery:
      type: object
      required:
        - burgerservicenummer
      properties:
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
    ReisdocumentenResponse:
      type: object
      properties:
        reisdocumenten:
          type: array
          items:
            $ref: '#/components/schemas/ReisdocumentUitgebreid'
    GbaReisdocumentenResponse:
      type: object
      properties:
        reisdocumenten:
          type: array
          items:
            $ref: '#/components/schemas/GbaReisdocument'
