openapi: 3.0.3
info:
  title: Reisdocument definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Reisdocumentnummer:
      type: string
      pattern: ^[a-zA-Z0-9]{9}$
    Burgerservicenummer:
      type: string
      pattern: ^[0-9]{9}$
      example: "555555021"
    AanduidingInhoudingOfVermissing:
      type: string
      pattern: ^(I|R|V|\.)$
    SoortReisdocument:
      type: string
      description: |
            Een code voor het soort reisdocument. Wordt gevuld met een code die voorkomen in de tabel 'Nederlands_Reisdocument' uit de Haal-Centraal-BRP-tabellen-bevragen API.
      pattern: ^[A-Z]{2}$
    ReisdocumentBasis:
      type: object
      description: |
                    Een document dat nodig is voor reizen naar het buitenland.

                    indicatieGeldig geeft aan of het reisdocument op dit moment nog geldig en in het bezit van de persoon is. Wordt gevuld op basis van de waarden die voorkomen in de tabel 'Geldig_Reisdocument' uit de Haal-Centraal-BRP-tabellen-bevragen API.
      properties:
        reisdocumentnummer:
          $ref: '#/components/schemas/Reisdocumentnummer' 
        indicatieGeldig:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
        geheimhoudingPersoongegevens:
          $ref: '#/components/schemas/GeheimhoudingPersoonsgegevens'
        opschortingBijhouding:
          $ref: 'opschortingbijhouding.yaml#/components/schemas/OpschortingBijhouding'
    Reisdocument:
      allOf:
        - $ref: '#/components/schemas/ReisdocumentBasis'
        - type: object
          description: |
                    Een document dat nodig is voor reizen naar het buitenland.

                    indicatieGeldig geeft aan of het reisdocument op dit moment nog geldig en in het bezit van de persoon is. Wordt gevuld op basis van de waarden die voorkomen in de tabel 'Geldig_Reisdocument' uit de Haal-Centraal-BRP-tabellen-bevragen API.
          properties:
            inOnderzoek:
              $ref: '#/components/schemas/ReisdocumentInOnderzoek'
    ReisdocumentUitgebreid:
      allOf:
        - $ref: '#/components/schemas/ReisdocumentBasis'
        - type: object
          description: |
                        Een document dat nodig is voor reizen naar het buitenland.

                        - indicatieGeldig geeft aan of het reisdocument op dit moment nog geldig en in het bezit van de persoon is. Wordt gevuld op basis van de waarden die voorkomen in de tabel 'Geldig_Reisdocument' uit de Haal-Centraal-BRP-tabellen-bevragen API.
                        - soortReisdocument wordt gevuld op basis van de waarden die voorkomen in de tabel 'Nederlands_Reisdocument' uit de Haal-Centraal-BRP-tabellen-bevragen API.
          properties:
            soortReisdocument:
              $ref: 'common.yaml#/components/schemas/Waardetabel'
            datumEindeGeldigheid:
              $ref: 'datum.yaml#/components/schemas/AbstractDatum'
            inOnderzoek:
              $ref: '#/components/schemas/ReisdocumentUitgebreidInOnderzoek'
    GbaReisdocument:
      type: object
      description: |
          Gegevens van een reisdocument die nodig zijn om te bepalen of het reisdocument nog geldig en in het bezit van de houder is, plus de identificatie van de houder.
      properties:
        reisdocumentnummer:
          $ref: '#/components/schemas/Reisdocumentnummer'
        soortReisdocument:
          $ref: 'common.yaml#/components/schemas/Waardetabel'
        datumEindeGeldigheid:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        datumInhoudingOfVermissing:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        aanduidingInhoudingOfVermissing:
          $ref: '#/components/schemas/AanduidingInhoudingOfVermissing'
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
        geheimhoudingPersoongegevens:
          $ref: '#/components/schemas/GbaGeheimhoudingPersoonsgegevens'
        opschortingBijhouding:
          $ref: 'opschortingbijhouding.yaml#/components/schemas/GbaOpschortingBijhouding'
        persoonInOnderzoek:
          $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
        reisdocumentInOnderzoek:
          $ref: 'gba-inonderzoek.yaml#/components/schemas/GbaInOnderzoek'
    ReisdocumentenQuery:
      type: object
      required:
        - burgerservicenummer
      properties:
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
    ReisdocumentenResponse:
      type: object
      properties:
        reisdocumenten:
          type: array
          items:
            $ref: '#/components/schemas/ReisdocumentUitgebreid'
    GbaReisdocumentenResponse:
      type: object
      properties:
        reisdocumenten:
          type: array
          items:
            $ref: '#/components/schemas/GbaReisdocument'
    InOnderzoek:
      type: object
      properties:
        datumIngangOnderzoek:
          $ref: 'datum.yaml#/components/schemas/AbstractDatum'
    ReisdocumentInOnderzoek:
      description: |
        Geeft aan welke gegevens over het reisdocument in onderzoek zijn.
      allOf:
        - $ref: '#/components/schemas/InOnderzoek'
        - type: object
          properties:
            burgerservicenummer:
              type: boolean
            reisdocumentnummer:
              type: boolean
            indicatieGeldig:
              type: boolean
    ReisdocumentUitgebreidInOnderzoek:
      description: |
        Geeft aan welke gegevens over het reisdocument in onderzoek zijn.
      allOf:
        - $ref: '#/components/schemas/ReisdocumentInOnderzoek'
        - type: object
          properties:
            soortReisdocument:
              type: boolean
            datumEindeGeldigheid:
              type: boolean
    GbaGeheimhoudingPersoonsgegevens:
      type: integer
    GeheimhoudingPersoonsgegevens:
      description: |
        Gegevens mogen niet worden verstrekt aan derden / maatschappelijke instellingen.
      type: boolean