openapi: 3.0.3
info:
  title: Reisdocument definities
  version: 2.0.0
  contact: {}
paths: {}
components:
  schemas:
    Reisdocumentnummer:
      type: string
      pattern: ^[a-zA-Z0-9]{9}$
    Burgerservicenummer:
      type: string
      pattern: ^[0-9]{9}$
      example: "555555021"
    AanduidingInhoudingOfVermissing:
      type: string
      pattern: ^(I|R|V|\.)$
    GbaOverlijden:
      type: object
      properties:
        datum:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
    Reisdocument:
      type: object
      description: |
                    Een document dat nodig is voor reizen naar het buitenland.
      properties:
        indicatieGeldig:
          type: boolean
          description: Geeft aan of het reisdocument op dit moment nog geldig en in het bezit van de persoon is.
        burgerservicenummer:
          $ref: 'reisdocument.yaml#/components/schemas/Burgerservicenummer' 
    GbaReisdocument:
      type: object
      description: |
          Gegevens van een reisdocument die nodig zijn om te bepalen of het reisdocument nog geldig en in het bezit van de houder is, plus de identificatie van de houder.
      properties:
        datumEindeGeldigheid:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        datumInhoudingOfVermissing:
          $ref: 'datum.yaml#/components/schemas/GbaDatum'
        aanduidingInhoudingOfVermissing:
          $ref: '#/components/schemas/AanduidingInhoudingOfVermissing'
        burgerservicenummer:
          $ref: '#/components/schemas/Burgerservicenummer'
        overlijden:
          $ref: '#/components/schemas/GbaOverlijden'
        

