/* 
 * Reisdocumenten
 *
 * API voor het ontsluiten van gegevens van reisdocumenten uit de GBA en RNI.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IReisdocumentenApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>ReisdocumentHal</returns>
        ReisdocumentHal ReisdocumentenReisdocumentnummer (string reisdocumentnummer);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>ApiResponse of ReisdocumentHal</returns>
        ApiResponse<ReisdocumentHal> ReisdocumentenReisdocumentnummerWithHttpInfo (string reisdocumentnummer);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>Task of ReisdocumentHal</returns>
        System.Threading.Tasks.Task<ReisdocumentHal> ReisdocumentenReisdocumentnummerAsync (string reisdocumentnummer);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>Task of ApiResponse (ReisdocumentHal)</returns>
        System.Threading.Tasks.Task<ApiResponse<ReisdocumentHal>> ReisdocumentenReisdocumentnummerAsyncWithHttpInfo (string reisdocumentnummer);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ReisdocumentenApi : IReisdocumentenApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ReisdocumentenApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ReisdocumentenApi(String basePath)
        {
            this.Configuration = new Org.OpenAPITools.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReisdocumentenApi"/> class
        /// </summary>
        /// <returns></returns>
        public ReisdocumentenApi()
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.Default;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReisdocumentenApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ReisdocumentenApi(Org.OpenAPITools.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Org.OpenAPITools.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>ReisdocumentHal</returns>
        public ReisdocumentHal ReisdocumentenReisdocumentnummer (string reisdocumentnummer)
        {
             ApiResponse<ReisdocumentHal> localVarResponse = ReisdocumentenReisdocumentnummerWithHttpInfo(reisdocumentnummer);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>ApiResponse of ReisdocumentHal</returns>
        public ApiResponse<ReisdocumentHal> ReisdocumentenReisdocumentnummerWithHttpInfo (string reisdocumentnummer)
        {
            // verify the required parameter 'reisdocumentnummer' is set
            if (reisdocumentnummer == null)
                throw new ApiException(400, "Missing required parameter 'reisdocumentnummer' when calling ReisdocumentenApi->ReisdocumentenReisdocumentnummer");

            var localVarPath = "/reisdocumenten/{reisdocumentnummer}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/hal+json",
                "application/problem+json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (reisdocumentnummer != null) localVarPathParams.Add("reisdocumentnummer", this.Configuration.ApiClient.ParameterToString(reisdocumentnummer)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ReisdocumentenReisdocumentnummer", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ReisdocumentHal>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ReisdocumentHal) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ReisdocumentHal)));
        }

        /// <summary>
        ///  Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>Task of ReisdocumentHal</returns>
        public async System.Threading.Tasks.Task<ReisdocumentHal> ReisdocumentenReisdocumentnummerAsync (string reisdocumentnummer)
        {
             ApiResponse<ReisdocumentHal> localVarResponse = await ReisdocumentenReisdocumentnummerAsyncWithHttpInfo(reisdocumentnummer);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  Het ophalen van de gegevens van een REISDOCUMENT op basis van het reisdocumentnummer.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="reisdocumentnummer">Het nummer van het verstrekte Nederlandse reisdocument.</param>
        /// <returns>Task of ApiResponse (ReisdocumentHal)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ReisdocumentHal>> ReisdocumentenReisdocumentnummerAsyncWithHttpInfo (string reisdocumentnummer)
        {
            // verify the required parameter 'reisdocumentnummer' is set
            if (reisdocumentnummer == null)
                throw new ApiException(400, "Missing required parameter 'reisdocumentnummer' when calling ReisdocumentenApi->ReisdocumentenReisdocumentnummer");

            var localVarPath = "/reisdocumenten/{reisdocumentnummer}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/hal+json",
                "application/problem+json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (reisdocumentnummer != null) localVarPathParams.Add("reisdocumentnummer", this.Configuration.ApiClient.ParameterToString(reisdocumentnummer)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ReisdocumentenReisdocumentnummer", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ReisdocumentHal>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ReisdocumentHal) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ReisdocumentHal)));
        }

    }
}
