# coding: utf-8

# flake8: noqa

"""
    Reisdocumenten

    API voor het ontsluiten van gegevens van reisdocumenten uit de GBA en RNI.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.reisdocumenten_api import ReisdocumentenApi

# import ApiClient
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiException
# import models into sdk package
from openapi_client.models.aanduiding_inhouding_vermissing_reisdocument_enum import AanduidingInhoudingVermissingReisdocumentEnum
from openapi_client.models.bad_request_foutbericht import BadRequestFoutbericht
from openapi_client.models.bad_request_foutbericht_all_of import BadRequestFoutberichtAllOf
from openapi_client.models.datum_onvolledig import DatumOnvolledig
from openapi_client.models.foutbericht import Foutbericht
from openapi_client.models.hal_link import HalLink
from openapi_client.models.invalid_params import InvalidParams
from openapi_client.models.reisdocument import Reisdocument
from openapi_client.models.reisdocument_hal import ReisdocumentHal
from openapi_client.models.reisdocument_hal_all_of import ReisdocumentHalAllOf
from openapi_client.models.reisdocument_in_onderzoek import ReisdocumentInOnderzoek
from openapi_client.models.reisdocument_links import ReisdocumentLinks
from openapi_client.models.waardetabel import Waardetabel

